{% set name = "ukkonen" %}
{% set version = "1.1.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fc62ce0a5b5d57198d4dc0c6ebca406b41afca2b6681af5159a6709b47286377

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: true  # [py<310]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
    - wheel
    - setuptools
    - cffi >=1
  run:
    - python
    - cffi >=1

test:
  imports:
    - ukkonen
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/asottile/ukkonen
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Implementation of bounded Levenshtein distance (Ukkonen).
  description: Implementation of bounded Levenshtein distance (Ukkonen).
  doc_url: https://github.com/asottile/ukkonen
  dev_url: https://github.com/asottile/ukkonen

extra:
  recipe-maintainers:
    - tdegeus
    - deadsnakes-issues-bot
